spring:
  application:
    name: waterball-challenge

  datasource:
    url: jdbc:postgresql://localhost:5432/waterball_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA 設定 (自動建表)
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 伺服器 Port
server:
  port: 5000